[book]
authors = ["lzzsG"]
language = "en"
multilingual = false
src = "src"
title = "系统编程"


[output.html]
site-url = "/sysbook/"
default-theme = "light"
preferred-dark-theme = "light"


[output.html.playground]
editable = true